# Generated by Django 4.1.5 on 2023-01-22 13:12

from django.db import migrations

from main.services.models_service import extract_fixtures


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    data = extract_fixtures()
    db_alias = schema_editor.connection.alias

    for key, values in data.items():
        model = apps.get_model('main', key)
        for value in values:
            model.objects.using(db_alias).create(**value)


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    data = extract_fixtures()
    db_alias = schema_editor.connection.alias

    for key in data:
        model = apps.get_model('main', key)
        model.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),

    ]
