# Generated by Django 4.1.5 on 2023-02-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attachment_comment_follower_friend_vkuser_wall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screen_name', models.CharField(default=None, max_length=255, null=True)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('avatar', models.URLField(default=None, null=True)),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city')),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country')),
            ],
            options={
                'db_table': 'vk_group',
            },
        ),
        migrations.RemoveField(
            model_name='vkuser',
            name='profile_type',
        ),
        migrations.AlterField(
            model_name='wall',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vkuser'),
        ),
        migrations.DeleteModel(
            name='ProfileType',
        ),
        migrations.AddField(
            model_name='vkgroup',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vkuser'),
        ),
        migrations.AddField(
            model_name='wall',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vkgroup'),
        ),
    ]
