# Generated by Django 4.1.5 on 2023-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_wall_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='photo',
            field=models.TextField(),
        ),
    ]
