volumes:
  pgdata_ctd:
services:
  redis:
    image: redis:6.2-alpine
    command:
      - /bin/sh
      - -c
      - redis-server --appendonly yes --maxmemory 2G --maxmemory-policy volatile-lru
    restart: always
    ports:
      - "0.0.0.0:6379:6379"
    user: root
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 0.0.0.0:5672:5672
      - 0.0.0.0:15672:15672
    environment:
      - RABBITMQ_USER=marat
      - RABBITMQ_USERNAME=marat
      - RABBITMQ_PASSWORD=marat
      - RABBITMQ_DEFAULT_USER=marat
      - RABBITMQ_DEFAULT_PASS=marat
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  postgres:
    image: postgres:13.3
    volumes:
      - pgdata_ctd:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "0.0.0.0:5432:5432"